const types = {
  FETCH_MOVIES_STATED: 'FETCH_MOVIES_STATED',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE',
  TOGGLE_FAVOURITE: 'TOGGLE_FAVOURITE',
};

export default types;
