const types = {
  FETCH_MOVIES_STARTED: 'FETCH_MOVIES_STARTED',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE',
  FETCH_MOVIEBYID_STARTED: 'FETCH_MOVIEBYID_STARTED',
  FETCH_MOVIEBYID_SUCCESS: 'FETCH_MOVIEBYID_SUCCESS',
  FETCH_MOVIEBYID_FAILURE: 'FETCH_MOVIEBYID_FAILURE',

  TOGGLE_FAVOURITE: 'TOGGLE_FAVOURITE',
};

export default types;
